import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import 'swiper/css';
import 'swiper/css/pagination';
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Toaster } from "@/components/ui/sonner"
import Providers from "@/Providers";
import Breadcrumb from "@/components/layout/Breadcrumb";
import TopBanner from "@/components/layout/TopBanner";






const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}>
          <Providers>
            <TopBanner />
            <Navbar />
            <Breadcrumb />
            <main>{children}</main>
            <Toaster />
            <Footer />
          </Providers>
      </body>
    </html>
  );
}
